server:
  port: 8082
message: This is Okay right?

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8081/eureka}
     # defaultZone: http://localhost:8085/eureka
